import type { ChordQuality } from './musicTheory'

export interface GenreProfile {
  id: string
  name: string
  category: string
  defaultBpm: [number, number]
  defaultScale: string
  timeSignature: [number, number]
  progressions: string[][]
  sectionTemplate: { type: string; bars: number; energy: number; density: number }[]
  drumStyle: string
  bassStyle: string
  melodyStyle: string
  instruments: {
    drums: number
    bass: number
    chords: number
    melody: number
    pad?: number
    arpeggio?: number
    strings?: number
    lead?: number
    brass?: number
  }
  swing: number
  velocityRange: [number, number]
  trackRoles: string[]
}

export const GENRES: GenreProfile[] = [
  {
    id: 'pop',
    name: 'Pop',
    category: 'Popular',
    defaultBpm: [100, 130],
    defaultScale: 'major',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'V', 'vi', 'IV'],
      ['vi', 'IV', 'I', 'V'],
      ['I', 'vi', 'IV', 'V'],
      ['IV', 'V', 'vi', 'I'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.3, density: 0.4 },
      { type: 'verse', bars: 8, energy: 0.5, density: 0.6 },
      { type: 'pre-chorus', bars: 4, energy: 0.7, density: 0.75 },
      { type: 'chorus', bars: 8, energy: 0.9, density: 0.85 },
      { type: 'verse', bars: 8, energy: 0.5, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.95, density: 0.9 },
      { type: 'bridge', bars: 8, energy: 0.6, density: 0.5 },
      { type: 'chorus', bars: 8, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 4, energy: 0.4, density: 0.3 },
    ],
    drumStyle: 'four-on-floor-lite',
    bassStyle: 'root-fifth',
    melodyStyle: 'hook-focused',
    instruments: { drums: 0, bass: 33, chords: 0, melody: 81, pad: 89, arpeggio: 46 },
    swing: 0,
    velocityRange: [60, 110],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'pad'],
  },
  {
    id: 'rock',
    name: 'Rock',
    category: 'Popular',
    defaultBpm: [110, 150],
    defaultScale: 'mixolydian',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'IV', 'V', 'I'],
      ['I', 'bVII', 'IV', 'I'],
      ['vi', 'IV', 'I', 'V'],
      ['I', 'V', 'vi', 'IV'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.5, density: 0.5 },
      { type: 'verse', bars: 8, energy: 0.6, density: 0.65 },
      { type: 'chorus', bars: 8, energy: 0.95, density: 0.9 },
      { type: 'verse', bars: 8, energy: 0.6, density: 0.65 },
      { type: 'chorus', bars: 8, energy: 0.95, density: 0.9 },
      { type: 'bridge', bars: 8, energy: 0.7, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 4, energy: 0.5, density: 0.4 },
    ],
    drumStyle: 'rock-backbeat',
    bassStyle: 'driving-eighths',
    melodyStyle: 'power-intervals',
    instruments: { drums: 0, bass: 34, chords: 29, melody: 30, lead: 29 },
    swing: 0,
    velocityRange: [70, 120],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'lead'],
  },
  {
    id: 'hip-hop',
    name: 'Hip-Hop',
    category: 'Popular',
    defaultBpm: [80, 100],
    defaultScale: 'minor',
    timeSignature: [4, 4],
    progressions: [
      ['i', 'VI', 'III', 'VII'],
      ['i', 'iv', 'VI', 'V'],
      ['i', 'VII', 'VI', 'VII'],
      ['i', 'III', 'VI', 'VII'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.4, density: 0.5 },
      { type: 'verse', bars: 16, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.75, density: 0.7 },
      { type: 'verse', bars: 16, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.8, density: 0.75 },
      { type: 'bridge', bars: 8, energy: 0.5, density: 0.45 },
      { type: 'outro', bars: 4, energy: 0.35, density: 0.35 },
    ],
    drumStyle: 'boom-bap',
    bassStyle: 'sub-808',
    melodyStyle: 'sparse-motif',
    instruments: { drums: 0, bass: 38, chords: 4, melody: 81, pad: 89 },
    swing: 0.08,
    velocityRange: [50, 100],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'pad'],
  },
  {
    id: 'house',
    name: 'House',
    category: 'Electronic',
    defaultBpm: [120, 128],
    defaultScale: 'minor',
    timeSignature: [4, 4],
    progressions: [
      ['i', 'VI', 'III', 'VII'],
      ['i', 'iv', 'VI', 'V'],
      ['i', 'VII', 'VI', 'VII'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 8, energy: 0.35, density: 0.4 },
      { type: 'build-up', bars: 8, energy: 0.65, density: 0.7 },
      { type: 'drop', bars: 16, energy: 0.95, density: 0.9 },
      { type: 'breakdown', bars: 8, energy: 0.4, density: 0.35 },
      { type: 'build-up', bars: 8, energy: 0.7, density: 0.75 },
      { type: 'drop', bars: 16, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 8, energy: 0.35, density: 0.3 },
    ],
    drumStyle: 'four-on-floor',
    bassStyle: 'sidechain-groove',
    melodyStyle: 'arpeggiated',
    instruments: { drums: 0, bass: 38, chords: 81, melody: 81, pad: 89, arpeggio: 81 },
    swing: 0,
    velocityRange: [55, 105],
    trackRoles: ['drums', 'bass', 'chords', 'arpeggio', 'pad', 'melody'],
  },
  {
    id: 'techno',
    name: 'Techno',
    category: 'Electronic',
    defaultBpm: [125, 140],
    defaultScale: 'minor',
    timeSignature: [4, 4],
    progressions: [
      ['i', 'i', 'VI', 'VII'],
      ['i', 'VII', 'i', 'VII'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 16, energy: 0.3, density: 0.35 },
      { type: 'build-up', bars: 8, energy: 0.6, density: 0.65 },
      { type: 'drop', bars: 16, energy: 0.9, density: 0.85 },
      { type: 'breakdown', bars: 8, energy: 0.35, density: 0.3 },
      { type: 'drop', bars: 16, energy: 1.0, density: 0.95 },
      { type: 'outro', bars: 8, energy: 0.3, density: 0.25 },
    ],
    drumStyle: 'techno-driving',
    bassStyle: 'rolling-sub',
    melodyStyle: 'minimal-motif',
    instruments: { drums: 0, bass: 38, chords: 81, melody: 81, arpeggio: 82, lead: 80 },
    swing: 0,
    velocityRange: [60, 115],
    trackRoles: ['drums', 'bass', 'arpeggio', 'lead', 'pad'],
  },
  {
    id: 'industrial',
    name: 'Industrial',
    category: 'Industrial',
    defaultBpm: [100, 140],
    defaultScale: 'phrygian',
    timeSignature: [4, 4],
    progressions: [
      ['i', 'bII', 'i', 'VII'],
      ['i', 'bVI', 'bVII', 'i'],
      ['i', 'bII', 'bVI', 'bVII'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.5, density: 0.5 },
      { type: 'verse', bars: 8, energy: 0.7, density: 0.75 },
      { type: 'chorus', bars: 8, energy: 0.95, density: 0.9 },
      { type: 'breakdown', bars: 4, energy: 0.4, density: 0.35 },
      { type: 'build-up', bars: 4, energy: 0.8, density: 0.85 },
      { type: 'drop', bars: 8, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 4, energy: 0.45, density: 0.4 },
    ],
    drumStyle: 'industrial-metallic',
    bassStyle: 'distorted-pulse',
    melodyStyle: 'dissonant-motif',
    instruments: { drums: 0, bass: 38, chords: 62, melody: 62, lead: 80, pad: 89 },
    swing: 0,
    velocityRange: [75, 127],
    trackRoles: ['drums', 'bass', 'chords', 'lead', 'pad'],
  },
  {
    id: 'jazz',
    name: 'Jazz',
    category: 'Popular',
    defaultBpm: [100, 160],
    defaultScale: 'dorian',
    timeSignature: [4, 4],
    progressions: [
      ['ii', 'V', 'I', 'VI'],
      ['I', 'vi', 'ii', 'V'],
      ['iii', 'vi', 'ii', 'V'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.4, density: 0.45 },
      { type: 'verse', bars: 8, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.7, density: 0.7 },
      { type: 'bridge', bars: 8, energy: 0.65, density: 0.65 },
      { type: 'chorus', bars: 8, energy: 0.75, density: 0.75 },
      { type: 'outro', bars: 4, energy: 0.4, density: 0.4 },
    ],
    drumStyle: 'swing-ride',
    bassStyle: 'walking',
    melodyStyle: 'bebop-lines',
    instruments: { drums: 0, bass: 33, chords: 0, melody: 66, pad: 89 },
    swing: 0.33,
    velocityRange: [45, 95],
    trackRoles: ['drums', 'bass', 'chords', 'melody'],
  },
  {
    id: 'metal',
    name: 'Metal',
    category: 'Industrial',
    defaultBpm: [140, 200],
    defaultScale: 'phrygian',
    timeSignature: [4, 4],
    progressions: [
      ['i', 'bVI', 'bVII', 'i'],
      ['i', 'bII', 'i', 'VII'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.7, density: 0.7 },
      { type: 'verse', bars: 8, energy: 0.85, density: 0.85 },
      { type: 'chorus', bars: 8, energy: 1.0, density: 1.0 },
      { type: 'breakdown', bars: 4, energy: 0.6, density: 0.55 },
      { type: 'chorus', bars: 8, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 4, energy: 0.65, density: 0.6 },
    ],
    drumStyle: 'double-kick',
    bassStyle: 'palm-muted-roots',
    melodyStyle: 'power-intervals',
    instruments: { drums: 0, bass: 34, chords: 30, melody: 30, lead: 29 },
    swing: 0,
    velocityRange: [85, 127],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'lead'],
  },
  {
    id: 'r-and-b',
    name: 'R&B',
    category: 'Popular',
    defaultBpm: [70, 95],
    defaultScale: 'minor',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'vi', 'IV', 'V'],
      ['vi', 'IV', 'I', 'V'],
      ['ii', 'V', 'I', 'vi'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.35, density: 0.4 },
      { type: 'verse', bars: 8, energy: 0.5, density: 0.55 },
      { type: 'pre-chorus', bars: 4, energy: 0.65, density: 0.7 },
      { type: 'chorus', bars: 8, energy: 0.85, density: 0.8 },
      { type: 'verse', bars: 8, energy: 0.5, density: 0.55 },
      { type: 'chorus', bars: 8, energy: 0.9, density: 0.85 },
      { type: 'bridge', bars: 8, energy: 0.6, density: 0.5 },
      { type: 'outro', bars: 4, energy: 0.35, density: 0.3 },
    ],
    drumStyle: 'rnb-groove',
    bassStyle: 'syncopated-funk',
    melodyStyle: 'soulful-phrase',
    instruments: { drums: 0, bass: 33, chords: 5, melody: 54, pad: 89 },
    swing: 0.12,
    velocityRange: [50, 105],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'pad'],
  },
  {
    id: 'cinematic',
    name: 'Cinematic',
    category: 'Popular',
    defaultBpm: [60, 90],
    defaultScale: 'minor',
    timeSignature: [4, 4],
    progressions: [
      ['i', 'VI', 'III', 'VII'],
      ['i', 'iv', 'V', 'i'],
      ['i', 'bVI', 'bIII', 'bVII'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 8, energy: 0.25, density: 0.3 },
      { type: 'verse', bars: 8, energy: 0.45, density: 0.5 },
      { type: 'build-up', bars: 8, energy: 0.7, density: 0.75 },
      { type: 'drop', bars: 8, energy: 0.95, density: 0.9 },
      { type: 'breakdown', bars: 8, energy: 0.35, density: 0.35 },
      { type: 'build-up', bars: 8, energy: 0.75, density: 0.8 },
      { type: 'drop', bars: 8, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 8, energy: 0.3, density: 0.25 },
    ],
    drumStyle: 'orchestral-perc',
    bassStyle: 'timpani-low',
    melodyStyle: 'epic-theme',
    instruments: { drums: 0, bass: 43, chords: 48, melody: 73, strings: 48, pad: 89 },
    swing: 0,
    velocityRange: [40, 110],
    trackRoles: ['drums', 'bass', 'strings', 'melody', 'pad', 'chords'],
  },
  {
    id: 'trance',
    name: 'Trance',
    category: 'Electronic',
    defaultBpm: [130, 145],
    defaultScale: 'major',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'V', 'vi', 'IV'],
      ['vi', 'IV', 'I', 'V'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 16, energy: 0.3, density: 0.35 },
      { type: 'build-up', bars: 8, energy: 0.65, density: 0.7 },
      { type: 'drop', bars: 16, energy: 0.95, density: 0.9 },
      { type: 'breakdown', bars: 8, energy: 0.35, density: 0.3 },
      { type: 'build-up', bars: 8, energy: 0.75, density: 0.8 },
      { type: 'drop', bars: 16, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 8, energy: 0.3, density: 0.25 },
    ],
    drumStyle: 'four-on-floor',
    bassStyle: 'rolling-sub',
    melodyStyle: 'uplifting-lead',
    instruments: { drums: 0, bass: 38, chords: 81, melody: 81, arpeggio: 46, pad: 89 },
    swing: 0,
    velocityRange: [55, 110],
    trackRoles: ['drums', 'bass', 'arpeggio', 'melody', 'pad'],
  },
  {
    id: 'dubstep',
    name: 'Dubstep',
    category: 'Electronic',
    defaultBpm: [138, 150],
    defaultScale: 'minor',
    timeSignature: [4, 4],
    progressions: [
      ['i', 'bVI', 'bIII', 'bVII'],
      ['i', 'VII', 'VI', 'VII'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 8, energy: 0.35, density: 0.4 },
      { type: 'verse', bars: 8, energy: 0.55, density: 0.55 },
      { type: 'build-up', bars: 8, energy: 0.75, density: 0.8 },
      { type: 'drop', bars: 16, energy: 1.0, density: 1.0 },
      { type: 'breakdown', bars: 8, energy: 0.35, density: 0.3 },
      { type: 'drop', bars: 16, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 4, energy: 0.3, density: 0.25 },
    ],
    drumStyle: 'half-time-heavy',
    bassStyle: 'wobble-sub',
    melodyStyle: 'sparse-motif',
    instruments: { drums: 0, bass: 38, chords: 81, melody: 81, lead: 80 },
    swing: 0,
    velocityRange: [65, 127],
    trackRoles: ['drums', 'bass', 'chords', 'lead'],
  },
  {
    id: 'drum-and-bass',
    name: 'Drum & Bass',
    category: 'Electronic',
    defaultBpm: [170, 180],
    defaultScale: 'minor',
    timeSignature: [4, 4],
    progressions: [
      ['i', 'VI', 'III', 'VII'],
      ['i', 'iv', 'VI', 'V'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 8, energy: 0.4, density: 0.45 },
      { type: 'drop', bars: 16, energy: 0.95, density: 0.9 },
      { type: 'breakdown', bars: 8, energy: 0.35, density: 0.35 },
      { type: 'build-up', bars: 8, energy: 0.7, density: 0.75 },
      { type: 'drop', bars: 16, energy: 1.0, density: 1.0 },
      { type: 'outro', bars: 8, energy: 0.35, density: 0.3 },
    ],
    drumStyle: 'breakbeat-dnb',
    bassStyle: 'reese-sub',
    melodyStyle: 'atmospheric',
    instruments: { drums: 0, bass: 38, chords: 81, melody: 81, pad: 89 },
    swing: 0,
    velocityRange: [60, 115],
    trackRoles: ['drums', 'bass', 'pad', 'melody'],
  },
  {
    id: 'country',
    name: 'Country',
    category: 'Popular',
    defaultBpm: [90, 130],
    defaultScale: 'major',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'IV', 'V', 'I'],
      ['I', 'V', 'vi', 'IV'],
      ['I', 'vi', 'IV', 'V'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.4, density: 0.45 },
      { type: 'verse', bars: 8, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.8, density: 0.75 },
      { type: 'verse', bars: 8, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.85, density: 0.8 },
      { type: 'bridge', bars: 8, energy: 0.6, density: 0.55 },
      { type: 'outro', bars: 4, energy: 0.4, density: 0.35 },
    ],
    drumStyle: 'country-shuffle',
    bassStyle: 'root-fifth',
    melodyStyle: 'hook-focused',
    instruments: { drums: 0, bass: 33, chords: 25, melody: 73, strings: 48 },
    swing: 0.15,
    velocityRange: [55, 105],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'strings'],
  },
  {
    id: 'classical',
    name: 'Classical',
    category: 'Popular',
    defaultBpm: [60, 120],
    defaultScale: 'major',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'IV', 'V', 'I'],
      ['I', 'vi', 'IV', 'V'],
      ['I', 'V', 'vi', 'iii', 'IV', 'I', 'IV', 'V'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.3, density: 0.35 },
      { type: 'verse', bars: 8, energy: 0.5, density: 0.55 },
      { type: 'bridge', bars: 8, energy: 0.65, density: 0.7 },
      { type: 'chorus', bars: 8, energy: 0.8, density: 0.8 },
      { type: 'verse', bars: 8, energy: 0.5, density: 0.55 },
      { type: 'chorus', bars: 8, energy: 0.85, density: 0.85 },
      { type: 'outro', bars: 4, energy: 0.35, density: 0.3 },
    ],
    drumStyle: 'orchestral-perc',
    bassStyle: 'contrabass',
    melodyStyle: 'classical-theme',
    instruments: { drums: 0, bass: 43, chords: 48, melody: 73, strings: 48 },
    swing: 0,
    velocityRange: [35, 100],
    trackRoles: ['strings', 'melody', 'chords', 'bass'],
  },
  {
    id: 'ambient',
    name: 'Ambient',
    category: 'Electronic',
    defaultBpm: [60, 90],
    defaultScale: 'lydian',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'II', 'I', 'V'],
      ['I', 'vi', 'IV', 'I'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 8, energy: 0.2, density: 0.25 },
      { type: 'verse', bars: 16, energy: 0.35, density: 0.35 },
      { type: 'bridge', bars: 8, energy: 0.45, density: 0.4 },
      { type: 'outro', bars: 8, energy: 0.2, density: 0.2 },
    ],
    drumStyle: 'minimal-perc',
    bassStyle: 'drone-low',
    melodyStyle: 'atmospheric',
    instruments: { drums: 0, bass: 38, chords: 89, melody: 88, pad: 89 },
    swing: 0,
    velocityRange: [30, 80],
    trackRoles: ['pad', 'melody', 'bass', 'chords'],
  },
  {
    id: 'reggae',
    name: 'Reggae',
    category: 'Popular',
    defaultBpm: [70, 90],
    defaultScale: 'major',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'IV', 'I', 'V'],
      ['I', 'V', 'vi', 'IV'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.4, density: 0.45 },
      { type: 'verse', bars: 8, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.75, density: 0.7 },
      { type: 'verse', bars: 8, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.8, density: 0.75 },
      { type: 'outro', bars: 4, energy: 0.4, density: 0.35 },
    ],
    drumStyle: 'one-drop',
    bassStyle: 'syncopated-funk',
    melodyStyle: 'hook-focused',
    instruments: { drums: 0, bass: 33, chords: 24, melody: 76, pad: 89 },
    swing: 0.1,
    velocityRange: [50, 100],
    trackRoles: ['drums', 'bass', 'chords', 'melody'],
  },
  {
    id: 'latin',
    name: 'Latin',
    category: 'Popular',
    defaultBpm: [95, 130],
    defaultScale: 'major',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'IV', 'V', 'I'],
      ['ii', 'V', 'I', 'IV'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.45, density: 0.5 },
      { type: 'verse', bars: 8, energy: 0.6, density: 0.65 },
      { type: 'chorus', bars: 8, energy: 0.85, density: 0.8 },
      { type: 'verse', bars: 8, energy: 0.6, density: 0.65 },
      { type: 'chorus', bars: 8, energy: 0.9, density: 0.85 },
      { type: 'outro', bars: 4, energy: 0.45, density: 0.4 },
    ],
    drumStyle: 'latin-clave',
    bassStyle: 'syncopated-funk',
    melodyStyle: 'hook-focused',
    instruments: { drums: 0, bass: 33, chords: 24, melody: 73, strings: 48 },
    swing: 0.08,
    velocityRange: [55, 110],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'strings'],
  },
  {
    id: 'funk',
    name: 'Funk',
    category: 'Popular',
    defaultBpm: [100, 120],
    defaultScale: 'mixolydian',
    timeSignature: [4, 4],
    progressions: [
      ['I7', 'IV7', 'I7', 'V7'],
      ['i7', 'IV7', 'i7', 'V7'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.5, density: 0.55 },
      { type: 'verse', bars: 8, energy: 0.65, density: 0.7 },
      { type: 'chorus', bars: 8, energy: 0.85, density: 0.85 },
      { type: 'bridge', bars: 8, energy: 0.7, density: 0.65 },
      { type: 'chorus', bars: 8, energy: 0.9, density: 0.9 },
      { type: 'outro', bars: 4, energy: 0.5, density: 0.45 },
    ],
    drumStyle: 'funk-groove',
    bassStyle: 'syncopated-funk',
    melodyStyle: 'soulful-phrase',
    instruments: { drums: 0, bass: 33, chords: 5, melody: 66, brass: 61 },
    swing: 0.15,
    velocityRange: [55, 110],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'brass'],
  },
  {
    id: 'soul',
    name: 'Soul',
    category: 'Popular',
    defaultBpm: [70, 100],
    defaultScale: 'major',
    timeSignature: [4, 4],
    progressions: [
      ['I', 'vi', 'IV', 'V'],
      ['vi', 'IV', 'I', 'V'],
    ],
    sectionTemplate: [
      { type: 'intro', bars: 4, energy: 0.35, density: 0.4 },
      { type: 'verse', bars: 8, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.8, density: 0.75 },
      { type: 'verse', bars: 8, energy: 0.55, density: 0.6 },
      { type: 'chorus', bars: 8, energy: 0.85, density: 0.8 },
      { type: 'bridge', bars: 8, energy: 0.65, density: 0.6 },
      { type: 'outro', bars: 4, energy: 0.35, density: 0.3 },
    ],
    drumStyle: 'rnb-groove',
    bassStyle: 'syncopated-funk',
    melodyStyle: 'soulful-phrase',
    instruments: { drums: 0, bass: 33, chords: 5, melody: 54, strings: 48, brass: 61 },
    swing: 0.12,
    velocityRange: [45, 105],
    trackRoles: ['drums', 'bass', 'chords', 'melody', 'strings', 'brass'],
  },
]

export function getGenreById(id: string): GenreProfile {
  return GENRES.find((g) => g.id === id) ?? GENRES[0]!
}

export function parseRomanNumeral(roman: string): { degree: number; quality?: ChordQuality } {
  const map: Record<string, number> = {
    I: 1, II: 2, III: 3, IV: 4, V: 5, VI: 6, VII: 7,
    i: 1, ii: 2, iii: 3, iv: 4, v: 5, vi: 6, vii: 7,
    bII: 2, bIII: 3, bVI: 6, bVII: 7,
  }
  const base = roman.replace(/[°7+]/g, '')
  const degree = map[base] ?? 1
  let quality: ChordQuality | undefined
  if (roman.includes('7') && roman === roman.toUpperCase()) quality = 'dom7'
  else if (roman.includes('7')) quality = 'min7'
  else if (roman.includes('°')) quality = 'dim'
  else if (roman === roman.toLowerCase() && !roman.startsWith('b')) quality = 'minor'
  else if (roman.startsWith('b')) quality = 'major'
  return { degree, quality }
}
